[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Essential security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"

# Force correct MIME types for JavaScript files
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# API redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  for = "/auth/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"  
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"

# API redirect rule (keep before SPA fallback)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect apex (plintcart.io) to www primary domain
[[redirects]]
  from = "/*"
  to = "https://www.plintcart.io/:splat"
  status = 301
  force = true
  conditions = { Host = ["plintcart.io"] }

# SPA fallback - must be last to serve index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
